### ISSUE TITLE
lib/reap-worker.js 

### ISSUE THREAD

**Issue by clocked0ne** [valery-barysok/session-file-store#24]
The default permissions of the reap-worker.js file do not allow it to be executed on *nix systems, you should change the permissions of the file to be executable with chmod +x and commit it back into the repository.

```javascript
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at Object.exports.execFile (child_process.js:689:15)
    at Object.helpers.asyncReap (./node_modules/session-file-store/lib/session-file-helpers.js:85:20)
    at null.<anonymous> (./node_modules/session-file-store/lib/session-file-helpers.js:61:19)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)
```

To workaround this I have had to write a prestart package.json hook into my node app to run a script that resets the file permissions, otherwise this will be reset whenever the dependancy updates with npm install.

**Comment by valery-barysok** [comment]
will do it today later.

**Comment by valery-barysok** [comment]
The file was already with 0775 permissions. The issue was related to publishing under windows platform. I did publishing new version under linux platform and now it is ok. All new versions will be published under linux platform.
