### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by Bluejay47** [valery-barysok/session-file-store#37]
Any ideas as to why I am encountering this error message? It's happening constantly and the system is not deleting old sessions files. This is on a Ubuntu server.

{
	"date" : "Wed May 04 2016 01:20:43 GMT-0400 (EDT)",
	"process" : {
		"pid" : 25011,
		"uid" : 0,
		"gid" : 0,
		"cwd" : "[deleted]",
		"execPath" : "/usr/local/bin/node",
		"version" : "v5.4.0",
		"argv" : ["/usr/local/bin/node", "/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js"],
		"memoryUsage" : {
			"rss" : 46448640,
			"heapTotal" : 27110944,
			"heapUsed" : 23003032
		}
	},
	"os" : {
		"loadavg" : [0.0029296875, 0.0146484375, 0.04541015625],
		"uptime" : 1080963
	},
	"trace" : [{
			"column" : 11,
			"file" : "util.js",
			"function" : "exports._errnoException",
			"line" : 856,
			"method" : "_errnoException",
			"native" : false
		}, {
			"column" : 11,
			"file" : "internal/child_process.js",
			"function" : "ChildProcess.spawn",
			"line" : 298,
			"method" : "spawn",
			"native" : false
		}, {
			"column" : 9,
			"file" : "child_process.js",
			"function" : "exports.spawn",
			"line" : 362,
			"method" : "spawn",
			"native" : false
		}, {
			"column" : 15,
			"file" : "child_process.js",
			"function" : "Object.exports.execFile",
			"line" : 151,
			"method" : "exports.execFile",
			"native" : false
		}, {
			"column" : 20,
			"file" : "[deleted]/node_modules/session-file-store/lib/session-file-helpers.js",
			"function" : "Object.helpers.asyncReap",
			"line" : 93,
			"method" : "helpers.asyncReap",
			"native" : false
		}, {
			"column" : 19,
			"file" : "[deleted]/node_modules/session-file-store/lib/session-file-helpers.js",
			"function" : "null._repeat",
			"line" : 69,
			"method" : "_repeat",
			"native" : false
		}, {
			"column" : 11,
			"file" : "timers.js",
			"function" : "wrapper [as _onTimeout]",
			"line" : 275,
			"method" : null,
			"native" : false
		}, {
			"column" : 15,
			"file" : "timers.js",
			"function" : "Timer.listOnTimeout",
			"line" : 92,
			"method" : "listOnTimeout",
			"native" : false
		}
	],
	"stack" : ["Error: spawn EACCES", "    at exports._errnoException (util.js:856:11)", "    at ChildProcess.spawn (internal/child_process.js:298:11)", "    at exports.spawn (child_process.js:362:9)", "    at Object.exports.execFile (child_process.js:151:15)", "    at Object.helpers.asyncReap ([deleted]/node_modules/session-file-store/lib/session-file-helpers.js:93:20)", "    at null._repeat ([deleted]/node_modules/session-file-store/lib/session-file-helpers.js:69:19)", "    at wrapper [as _onTimeout] (timers.js:275:11)", "    at Timer.listOnTimeout (timers.js:92:15)"],
	"level" : "error",
	"message" : "uncaughtException: spawn EACCES",
	"timestamp" : "2016-05-04T05:20:43.502Z"
}

**Comment by valery-barysok** [comment]
It seems like you have permission issue. May be you executed your app under the user with not sufficient permissions. Check owner of old file if it equals to current user.

**Comment by Bluejay47** [comment]
Based on this thread https://github.com/valery-barysok/session-file-store/issues/24 I did a chmod +x on the file reap-worker.js located in the node_modules directory and it works correctly for now, but I have no idea why this would be necessary.

**Comment by valery-barysok** [comment]
It needs because it has to be executed as worker for reaping of stale session files. But I publish session-file-store already with these permissions. May be it is not true for latest version (needs to be checked) or may be you delivered this module in wrong way.

**Comment by valery-barysok** [comment]
no activity.
