### ISSUE TITLE
encryption with cbor encoding does not work

### ISSUE THREAD

**Issue by valery-barysok** [valery-barysok/session-file-store#50]
encryption with cbor encoding leads to error 'Unsupported input format: undefined' while try to decrypt and decode.
```
app.use(session({
    store: new FileStore({
      fileExtension: '.cbor',
      secret: '',
      encoding: 'utf8',
      encoder: cbor.encode,
      decoder: cbor.decode
    }),
    secret: 'keyboard cat',
    resave: true,
    saveUninitialized: true
  })
);
```

**Comment by valery-barysok** [comment]
but works with
app.use(session({
    store: new FileStore({
      fileExtension: '.cbor',
      secret: '',
      encryptEncoding: null,
      encoding: null,
      encoder: cbor.encode,
      decoder: cbor.decode
    }),
    secret: 'keyboard cat',
    resave: true,
    saveUninitialized: true
  })
);

**Comment by TYoung86** [comment]
is that the exact error message? can you paste the backtrace? I'll try it in a few minutes...

**Comment by TYoung86** [comment]
Just FYI, unlike JSON which is a textual encoding, CBOR is a binary encoding, so has no encoding character set... internally it encodes utf8 (some utf16) strings and packs other values as binary.

**Comment by TYoung86** [comment]
Hm. Something's not right. Not outputting hex anymore.

**Comment by TYoung86** [comment]
`
Uncaught AssertionError: expected [Error: Unsupported input format: undefined] to not exist
      at Assertion.<anonymous> (C:\Users\tyler\Documents\nodelibs\session-file-store\node_modules\chai\lib\chai\core\assertions.js:346:10)
      at Assertion.Object.defineProperty.get (C:\Users\tyler\Documents\nodelibs\session-file-store\node_modules\chai\lib\chai\utils\addProperty.js:35:29)
      at C:\Users\tyler\Documents\nodelibs\session-file-store\test\helpers.js:456:29
      at readCallback (C:\Users\tyler\Documents\nodelibs\session-file-store\lib\session-file-helpers.js:188:11)
      at C:\Users\tyler\Documents\nodelibs\session-file-store\node_modules\graceful-fs\graceful-fs.js:78:16
      at tryToString (fs.js:455:3)
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
`

**Comment by TYoung86** [comment]
Not sure if a problem with `graceful-fs` or encoding option not being passed somewhere.

**Comment by TYoung86** [comment]
I tried splitting the decrypt and decode parts of `helpers.get` out into seperate exceptions, and the exception is coming from `cbor.decode`. The error might be outside of the project.

`Uncaught Error: Unsupported input format: undefined
      at Object.api.decode [as decoder] (C:\Users\tyler\Documents\nodelibs\session-file-store\node_modules\cbor-sync\main.js:387:11)
      at readCallback (C:\Users\tyler\Documents\nodelibs\session-file-store\lib\session-file-helpers.js:182:30)
      at C:\Users\tyler\Documents\nodelibs\session-file-store\node_modules\graceful-fs\graceful-fs.js:78:16
      at tryToString (fs.js:455:3)
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)`

**Comment by TYoung86** [comment]
According to https://github.com/ARMmbed/cbor-sync/blob/master/main.js#L387 ... to make this work, you'd have to change the decode operation to incorporate the format for non-binary input.

e.g. this works;
`  var ENCRYPT_CBOR_HEX_OPTIONS = helpers.defaults({
    path: FIXTURE_ENCRYPTED_SESSIONS_PATH,
    logFn: NOOP_FN,
    fileExtension: '.aesctrcborhex',
    encrypt: true,
    encoding: 'utf8',
    encryptEncoding: 'hex',
    encoder: function(x) { return cbor.encode(x, 'hex'); },
    decoder: function(x) { return cbor.decode(x, 'hex'); }
  });`

**Comment by TYoung86** [comment]
I should also note that really ... the encoding and encryptEncoding should always be null for encryption for best performance and smallest size for now. working with hex characters as output was just for backwards compatibility with the way it was written in the first place.

**Comment by valery-barysok** [comment]
I agree that it is misconfiguration and currently we have enough details for other people who stuck with that.

**Comment by jas-** [comment]
Updating to the latest version should allow better functionality with handling transparent encryption support. It is best to expire any existing sessions prior to updating however.
