### ISSUE TITLE
logfn parameter not compatible with log4js?

### ISSUE THREAD

**Issue by loudking** [valery-barysok/session-file-store#52]
Hi I just tried to create session-file-store with parameter logFn but failed. Please suggest what to do.

code:
```
var log4js = require('log4js'); 
log4js.configure({
  "appenders": [{
    "type": "file",
    "filename": file_log,
    "category": "recon-frontend",
    "layout": {
      "type": "pattern",
      "pattern": "%d{yyyy-MM-dd hh:mm:ss.SSS} %m"
    }
  }
]});
var logger = log4js.getLogger('recon-frontend');
logger.setLevel('info');

var options = {
    name: 'connect.sid',
    store: new FileStore({logFn: logger.info}),
    secret: 'keyboard cat',
    resave: true,
    saveUninitialized: true
};
```

error:

```
frontend\node_modules\log4js\lib\logger.js:83
    if (logWritesEnabled && this.isLevelEnabled(level)) {
                                 ^

TypeError: this.isLevelEnabled is not a function
    at Object.Logger.(anonymous function) [as logFn] (frontend\node_modules\log4js\lib\logger.js:83:34)
    at ReadFileContext.readCallback (frontend\node_modules\session-file-store\lib\session-file-helpers.js:197:19)
    at ReadFileContext.callback (frontend\node_modules\session-file-store\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

**Comment by valery-barysok** [comment]
you need to wrap next way:

```js
var logFn = function (msg) {
    logger.info(msg)
};

new FileStore({ logFn: logFn });
```
