### ISSUE TITLE
FileStore.addListener causes memory leak?

### ISSUE THREAD

**Issue by loudking** [valery-barysok/session-file-store#54]
I didn't find any regulations for this warning but it is annoying. Please help. Warning message is:
```

(node) warning: possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at FileStore.addListener (events.js:239:17)
    at session (source\recon\frontend\node_modules\express-session\index.js:171:9)
    at Array.<anonymous> (source\recon\frontend\recons-frontend-server.js:116:5)
    at run (source\recon\frontend\node_modules\socket.io\lib\namespace.js:119:11)
    at Namespace.run (source\recon\frontend\node_modules\socket.io\lib\namespace.js:131:3)
    at Namespace.add (source\recon\frontend\node_modules\socket.io\lib\namespace.js:160:8)
    at Client.connect (source\recon\frontend\node_modules\socket.io\lib\client.js:76:20)
    at Server.onconnection (source\recon\frontend\node_modules\socket.io\lib\index.js:367:10)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
```

The warning points in my code at line 116, which is:

```
var io = require("socket.io")(server);
io.use(function(socket, next) {
    session(options)(socket.handshake, {}, next);         << This line.
});

```

**Comment by valery-barysok** [comment]
Did you try to see other session stores? all of them are event emitters by nature.

I do not really think it is specifically related to session-file-store. But if you sure that it is my issue then feel free continue to discuss it.
