### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by Grzegorzsa** [valery-barysok/session-file-store#69]
I've got some errors constantly reported by express server.

Windows 10/64
npm ver 6.1.0
node ver 10.5.0

{ [Error: EPERM: operation not permitted, rename 'V:\www\docs-viewer\sessions\4vNjE4HUhbBsrMUwtRdksqIaoFkHIxkE.json.4225269665' -> 'V:\www\docs-viewer\sessions\4vNjE4HUhbBsrMUwtRdksqIaoFkHIxkE.json']
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path:
   'V:\\www\\docs-viewer\\sessions\\4vNjE4HUhbBsrMUwtRdksqIaoFkHIxkE.json.4225269665',
  dest:
   'V:\\www\\docs-viewer\\sessions\\4vNjE4HUhbBsrMUwtRdksqIaoFkHIxkE.json' }

**Comment by valery-barysok** [comment]
looks like you have problem with permissions in this folder or may be it is related to simultaneous rename of files to the same file.

**Comment by acritelli** [comment]
Same issue here. Nothing special about the permissions on the directory: it's created automatically by the module.

Windows 10/64
NPM: 5.6.0
Node: 8.11.1

The error will intermittently show up and, when it does, it causes transient issues with those sessions. For example: a user may not be able to log in.

**Comment by ksfreitas** [comment]
Same here on Windows. This ocurrs due multiple session access (when cache is off, for example, this session is called for every resource like css, images, etc). 

Each session access try to save the `lastAccess` property. Due some concurrency problem, only one will save correctly.

I'm looking for solution and I will do a pull request to solve this.

**Comment by ksfreitas** [comment]
The problem is located in write-file-atomic library. Related issue: https://github.com/npm/write-file-atomic/issues/28

**Comment by iarna** [comment]
Hey, I just did a release yesterday with a bunch of fixes that may ease this issue a bit, specifically, it was previously leaking filehandles which may have made this worse. Can I get y'all to try updating to write-file-atomic@2.4.2 and see if that helps?

**Comment by valery-barysok** [comment]
@iarna, thanks. I will try to update dependency.

**Comment by JohnzBallad** [comment]
I'm having this issue as well. Does anyone have a fix?

**Comment by migueldaipre** [comment]
I'm having same issue. Does anyone have a fix ?

**Comment by JohnzBallad** [comment]
LokiStore solve this issue ;)

**Comment by davalapar** [comment]
Looked into this a bit, I'm quite certain it's `write-file-atomic` causing this.

I've encountered same range of errors in one of my projects on moderate to heavy amount of calls involving opening (and closing) of file descriptors, and renaming the files themselves.

Better approach is to literally just keep the file descriptors open during writes (on both files, asynchronously) then close them synchronously once done. No need for fancy file renames, since writes on files a and b can be done asynchronous-yet-one-after-another way.

**Comment by kdemarest** [comment]
I'm getting the same problem:
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open ...
It started after I upgraded from a prior version of session-file-store.

**Comment by jas-** [comment]
In all cases have any of the following been inspected?

1. Deleted files in use?
2. Does the ENOENT files actually exist and correlate to the requested session?
3. Upon upgrade has the existing server sessions been cleared or were they left to resume?

**Comment by kbjwes77** [comment]
I'm still getting this error. Running on latest version of node.js on an AWS linux VM.

> [session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/asdjasdaodhhfiqwf.json'

All dependencies are up to date. Any ideas why this could still be happening?

**Comment by Adepusrikanth9666** [comment]
C:\>browser-sync start --server --directory --files "**/*"
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, watch 'C:\Documents and Settings'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1339:11)
    at createFsWatchInstance (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:38:15)
    at setFsWatchListener (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (fs.js:168:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\index.js:260:10)
    at createFsWatchInstance (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:40:5)
    at setFsWatchListener (C:\Users\sainaveen\AppData\Roaming\npm\node_modules\browser-sync\node_modules\chokidar\lib\nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:168:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Documents and Settings',
  filename: 'C:\\Documents and Settings'
}


i have an error while isstalling the browser sync any one can help pz?

**Comment by dillu24** [comment]
Currently I have the same issue `Error: EPERM: operation not permitted, rename`

Is there a fix planned for this?

**Comment by valery-barysok** [comment]
Can you figure out with permissions on your system and check that issue is not there and path is correct? Try with some other short path with right permissions without whitespaces ?

**Comment by dillu24** [comment]
> 
> 
> Can you figure out with permissions on your system and check that issue is not there and path is correct? Try with some other short path with right permissions without whitespaces ? and provide full details about your issue context, please.

The path and permissions are correct, as the files are correctly outputted in the desired folder.

**Comment by alexb-uk** [comment]
This appears to be a Windows Security Virus & Threat Protection issue.

Disabling "Real-time protection" removes the error. Some people appear to have had luck adding the folder to the exclusion list but this did not work for me.

Since we only use Windows on dev environments I will probably just live with the error message since it doesn't appear to effect session storage.

**Comment by aklietz** [comment]
The problem is that when a Windows AV software package spots a new file being created it likes to quietly map it for snooping (`CreateFileMapping`), and if that newborn file is also being renamed by another process immediately after creation (e.g, to move-replace another file) node's `MoveFileEx` can fail with a transient ERROR_ACCESS_DENIED (aka EPERM). I've used Process Monitor to spot Microsoft's own `MsMpEng.exe` in Windows Defender doing this in my sessions folder several times a day.

`session-file-store` is still using an old version of `write-file-atomic` from 2017 (1.3.1), which I suspect does not implement the necessary backoff-retry mechanism correctly (or maybe the fault is in its underlying transitive dependency on an old version of `graceful-fs`; the facts are confusing to me). 

The current version of `write-file-atomic` is 3.0.3. It has dropped the dependency on `graceful-fs`. I tested it on my devel server against `session-file-store` with npm-force-resolutions and it seems to work wonderfully.

The main reason for the breaking change was their dropping of support for node 6.   If `session-file-store` bumped a major version with a change log notice about also dropping support for node 6 it might be able to use it as-is. (Obviously it will need a lot of testing first.)

**Comment by valery-barysok** [comment]
@aklietz, will try to update dependencies soon.

**Comment by aklietz** [comment]
@valery-barysok, thanks.  I hit the EPERM problem again even with `write-file-atomic` bumped up to 3.0.3, although it is happening a lot more rarely now.   Taking out `graceful-fs` seems to help but it's not a complete fix.

I had assumed that node 12.18.3 implemented the exponential fallback heuristic for `fs.rename()` to retry MoveFileEx several times before giving up. However, a cursory inspection of the source shows this does not appear to be the case. 

I looked at `graceful-fs` again, and while it does appear to be doing the exponential fallback heuristic for certain file operations, `fs.rename()` does not appear to be one of them.

Microsoft does provide a method of calling `NtSetInformationFile` with `FILE_RENAME_INFORMATION` that appears to do an [atomic rename](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information) on the same volume.

**Comment by KEMBL** [comment]
How to update `session-file-store` deep dependency `write-file-atomic` version using `resolutions` in `package.json`

`"resolutions": {
    "session-file-store/**/write-file-atomic": "^3.0.3"
  },`

`session-file-store` works fine, but still, `Error: EPERM: operation not permitted, rename` errors appearing despite the fact realtime-protection is off

**Comment by sakarit** [comment]
@valery-barysok Please release the newest version (1.5.0) to npm!

**Comment by valery-barysok** [comment]
@sakarit, i do know how i missed that, thank you. Will do soon.

**Comment by JoshMayberry** [comment]
I am still seeing this issue, even though `write-file-atomic` is on version 3.0.3

**Comment by aklietz** [comment]
>@valery-barysok, thanks. I hit the EPERM problem again even with `write-file-atomic` bumped up to 3.0.3, although it is happening a lot more rarely now. Taking out `graceful-fs` seems to help but it's not a complete fix.
> 
> I had assumed that node 12.18.3 implemented the exponential fallback heuristic for `fs.rename()` to retry MoveFileEx several times before giving up. However, a cursory inspection of the source shows this does not appear to be the case.
> 
> I looked at `graceful-fs` again, and while it does appear to be doing the exponential fallback heuristic for certain file operations, `fs.rename()` does not appear to be one of them.
> 
> Microsoft does provide a method of calling `NtSetInformationFile` with `FILE_RENAME_INFORMATION` that appears to do an [atomic rename](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information) on the same volume.

@JoshMayberry, @valery-barysok The proper way to resolve this issue is to fix Node so that `fs.rename()` does an atomic rename using `NtSetInformationFile FILE_RENAME_INFORMATION`  instead of calling `MoveFileEx`.

**Comment by aklietz** [comment]
I checked the latest NodeJS (16.9.1) and confirmed that `fs.rename` still wrongly calls `MoveFileEx` when it ought to be calling `NtSetInformationFile` with the argument [FILE_RENAME_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information) with the flags `FILE_RENAME_REPLACE_IF_EXISTS | FILE_RENAME_POSIX_SEMANTICS`. 

I suspect that the failure to request `FILE_RENAME_POSIX_SEMANTICS` is the root of the problem.  `fs.rename` assumes that rename() is atomic per the POSIX (Linux) standard but is failing to ask Windows to provide said semantics.

**Comment by Ludovicmanga** [comment]
Hi, I use node Js, with passport and express-session.
I kept blocked for more than a day in it until I realize that, due to a design error in my react frontend, I was just sending way too many requests to my backend at a specific moment, in a very short time (like a hundred requests in a few seconds). Making sure that I don't send these tons of requests solved it for me.

I could not explain why the fact there is too many requests blocked the access though

**Comment by programemail10** [comment]
i have the same issue
on windows server 
node v 21... & 18.14.0
no real time antyvirus
write-file-atomic 3.0.3
