### ISSUE TITLE
[Node 13] The argument 'encoding' is invalid for data of length 185

### ISSUE THREAD

**Issue by taigah** [valery-barysok/session-file-store#79]
The module doesn't work with node 13, I get this error when the session is saved

```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'encoding' is invalid for data of length 185. Received 'hex'
    at validateEncoding (internal/validators.js:148:11)
    at Decipheriv.update (internal/crypto/cipher.js:157:3)
    at Object.decrypt (node_modules/session-file-store/lib/session-file-helpers.js:409:24)
    at readCallback (node_modules/session-file-store/lib/session-file-helpers.js:173:79)
    at node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

My config

```javascript
const FileStore = require('session-file-store')(session)
const store = new FileStore({
  secret: secretKey
})

app.use(session({
  secret: secretKey,
  resave: false,
  saveUninitialized: false,
  cookie: { path: '/', httpOnly: true, maxAge: null },
  store
}))
```

**Comment by opensourcegeek** [comment]
@taigah Did you find the fix for it? I've been hit with the same issue

**Comment by taigah** [comment]
> @taigah Did you find the fix for it? I've been hit with the same issue

I did not, sorry. :/

**Comment by jas-** [comment]
The `crypto.createDecipher()` function has been deprecated in favor of the `crypto.createDecipherIV()` API. The PR #81 should resolve this.

**Comment by valery-barysok** [comment]
I'll publish new version with mentioned PR on weekend.

**Comment by karlhorky** [comment]
@valery-barysok thanks for merging #81! Could you publish a new version?

**Comment by valery-barysok** [comment]
> @valery-barysok thanks for merging #81! Could you publish a new version?

done.

**Comment by karlhorky** [comment]
No worries, thanks!

**Comment by karlhorky** [comment]
Can this issue be closed now? cc @taigah @opensourcegeek

**Comment by opensourcegeek** [comment]
@karlhorky Yea sure, looks good to me.
