### ISSUE TITLE
Adding a secret causes a crash

### ISSUE THREAD

**Issue by MattRiddell** [valery-barysok/session-file-store#88]
If I check out a fresh version of this repo and make the following change to `examples/express-example/app.js`:

from:

```JavaScript
store: new FileStore,
```

to 

```JavaScript
store: new FileStore(
        {
            secret: 'bla',
        }
),
```

Any access to localhost:1337 crashes with:

```zsh
❯ npm start

> file-session@0.0.1 start /Users/matt/Sites/session-file-store/examples/express-example
> node app.js

Example app listening at http://:::1337
buffer.js:207
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at Kruptein._derive_key (/Users/matt/Sites/session-file-store/examples/express-example/node_modules/kruptein/lib/kruptein.js:357:14)
    at Kruptein.get (/Users/matt/Sites/session-file-store/examples/express-example/node_modules/kruptein/lib/kruptein.js:170:10)
    at Object.decrypt (/Users/matt/Sites/session-file-store/examples/express-example/node_modules/session-file-store/lib/session-file-helpers.js:403:22)
    at readCallback (/Users/matt/Sites/session-file-store/examples/express-example/node_modules/session-file-store/lib/session-file-helpers.js:179:44)
    at /Users/matt/Sites/session-file-store/examples/express-example/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

That code is:

```Javascript
    // If a salt was NOT supplied, create one
    //   References: RFC 4086, 5084, SP 800-57P1, 800-108 & 800-132
    salt = (typeof salt !== "function") ?
      Buffer.from(salt) : this.crypto.randomBytes(128);
```

But `salt` is undefined.  Hardcoding one just makes another error.

Any ideas where I should go from here or something I'm missing?

**Comment by MattRiddell** [comment]
I noticed you had a test for it that worked so I dug a little deeper.

If you have a sessions directory already and it wasn't encrypted it'll crash once you add the option.

I.E. you need to start with the secret squirrel before ever testing it.

**Comment by jas-** [comment]
This will occur when a client sends a cookie that references a non-encrypted session after you have enabled transparent encryption support. You should force expire any existing sessions *before* enabling this functionality.

**Comment by jas-** [comment]
@MattRiddell Is this still an issue?
